export const characters =
    [
        { 'key': 'mario', 'index': 1, 'name': 'Mario', },
        { 'key': 'donkey', 'index': 2, 'name': 'Donkey Kong', },
        { 'key': 'link', 'index': 3, 'name': 'Link', },
        { 'key': 'samus', 'index': 4, 'name': 'Samus', },
        { 'key': 'samusd', 'index': 5, 'name': 'Dark Samus', },
        { 'key': 'yoshi', 'index': 6, 'name': 'Yoshi', },
        { 'key': 'kirby', 'index': 7, 'name': 'Kirby', },
        { 'key': 'fox', 'index': 8, 'name': 'Fox', },
        { 'key': 'pikachu', 'index': 9, 'name': 'Pikachu', },
        { 'key': 'luigi', 'index': 10, 'name': 'Luigi', },
        { 'key': 'ness', 'index': 11, 'name': 'Ness', },
        { 'key': 'captain', 'index': 12, 'name': 'Captain Falcon', },
        { 'key': 'purin', 'index': 13, 'name': 'Jiggly Puff', },
        { 'key': 'peach', 'index': 14, 'name': 'Peach', },
        { 'key': 'daisy', 'index': 15, 'name': 'Daisy', },
        { 'key': 'koopa', 'index': 16, 'name': 'koopa', },
        { 'key': 'ice_climber', 'index': 17, 'name': 'Ice Climbers', },
        { 'key': 'sheik', 'index': 18, 'name': 'Sheik', },
        { 'key': 'zelda', 'index': 19, 'name': 'Zelda', },
        { 'key': 'mariod', 'index': 20, 'name': 'Dr. Mario', },
        { 'key': 'pichu', 'index': 21, 'name': 'Pichu', },
        { 'key': 'falco', 'index': 22, 'name': 'Falco', },
        { 'key': 'marth', 'index': 23, 'name': 'Marth', },
        { 'key': 'lucina', 'index': 24, 'name': 'Lucina', },
        { 'key': 'younglink', 'index': 25, 'name': 'Young Link', },
        { 'key': 'ganon', 'index': 26, 'name': 'Ganon', },
        { 'key': 'mewtwo', 'index': 27, 'name': 'Mewtwo', },
        { 'key': 'roy', 'index': 28, 'name': 'Roy', },
        { 'key': 'chrom', 'index': 29, 'name': 'Chrom', },
        { 'key': 'gamewatch', 'index': 30, 'name': 'Mr. Game & Watch', },
        { 'key': 'metaknight', 'index': 31, 'name': 'Meta Knight', },
        { 'key': 'pit', 'index': 32, 'name': 'Pit', },
        { 'key': 'pitb', 'index': 33, 'name': 'Dark Pit', },
        { 'key': 'szerosuit', 'index': 34, 'name': 'Zero Suit Samus', },
        { 'key': 'wario', 'index': 35, 'name': 'Wario', },
        { 'key': 'snake', 'index': 36, 'name': 'Snake', },
        { 'key': 'ike', 'index': 37, 'name': 'Ike', },
        { 'key': 'ptrainer', 'index': 38, 'name': 'Pokemon Trainer', },
        { 'key': 'diddy', 'index': 42, 'name': 'Diddy Kong', },
        { 'key': 'lucas', 'index': 43, 'name': 'Lucas', },
        { 'key': 'sonic', 'index': 44, 'name': 'Sonic', },
        { 'key': 'dedede', 'index': 45, 'name': 'King Dedede', },
        { 'key': 'pikmin', 'index': 46, 'name': 'Olimar', },
        { 'key': 'lucario', 'index': 47, 'name': 'Lucario', },
        { 'key': 'robot', 'index': 48, 'name': 'R.O.B.', },
        { 'key': 'toonlink', 'index': 49, 'name': 'Toon Link', },
        { 'key': 'wolf', 'index': 50, 'name': 'Wolf', },
        { 'key': 'murabito', 'index': 51, 'name': 'Villager', },
        { 'key': 'rockman', 'index': 52, 'name': 'Mega Man', },
        { 'key': 'wiifit', 'index': 53, 'name': 'Wii Fit Trainer', },
        { 'key': 'rosetta', 'index': 54, 'name': 'Rosalina & Luma', },
        { 'key': 'littlemac', 'index': 55, 'name': 'Little Mac', },
        { 'key': 'gekkouga', 'index': 56, 'name': 'Greninja', },
        { 'key': 'palutena', 'index': 57, 'name': 'Palutena', },
        { 'key': 'pacman', 'index': 58, 'name': 'Pac-man', },
        { 'key': 'reflet', 'index': 59, 'name': 'Robin', },
        { 'key': 'shulk', 'index': 60, 'name': 'Shulk', },
        { 'key': 'koopajr', 'index': 61, 'name': 'Bowser Jr.', },
        { 'key': 'duckhunt', 'index': 62, 'name': 'Duck Hunt', },
        { 'key': 'ryu', 'index': 63, 'name': 'Ryu', },
        { 'key': 'ken', 'index': 64, 'name': 'Ken', },
        { 'key': 'cloud', 'index': 65, 'name': 'Cloud', },
        { 'key': 'kamui', 'index': 66, 'name': 'Corrin', },
        { 'key': 'bayonetta', 'index': 67, 'name': 'Bayonetta', },
        { 'key': 'richter', 'index': 68, 'name': 'Richter', },
        { 'key': 'inkling', 'index': 69, 'name': 'Inkling', },
        { 'key': 'ridley', 'index': 70, 'name': 'Ridley', },
        { 'key': 'krool', 'index': 71, 'name': 'King K. Rool', },
        { 'key': 'simon', 'index': 72, 'name': 'Simon', },
        { 'key': 'shizue', 'index': 73, 'name': 'Isabelle', },
        { 'key': 'gaogaen', 'index': 74, 'name': 'Incineroar', },
        { 'key': 'packun', 'index': 105, 'name': 'Piranha Plant-', },
        { 'key': 'jack', 'index': 106, 'name': 'Joker', },
        { 'key': 'brave', 'index': 107, 'name': 'Hero', },
        { 'key': 'buddy', 'index': 108, 'name': 'Banjo & Kazooie', },
        { 'key': 'dolly', 'index': 109, 'name': 'Terry', },
        { 'key': 'master', 'index': 110, 'name': 'Byleth', },
        { 'key': 'tantan', 'index': 111, 'name': 'Min Min', },
        { 'key': 'pickel', 'index': 112, 'name': 'Steve', },
        { 'key': 'edge', 'index': 113, 'name': 'Sephiroth', },
        { 'key': 'eflame_first', 'index': 115, 'name': 'Pyra', },
        { 'key': 'elight_first', 'index': 116, 'name': 'Mythra', },
        { 'key': 'demon', 'index': 119, 'name': 'Kazuya', },
        { 'key': 'trail', 'index': 120, 'name': 'Sora' },

    ]
